### ISSUE TITLE
Camera viepoint

### ISSUE THREAD

**Issue by wenyihan4396** [xheon/panoptic-reconstruction#16]
Excuse me, could you please opensource the code which can get camera parameter to capture this image. (same viewpoint with input image)
![image](https://user-images.githubusercontent.com/71435435/185745938-2c9eb46f-c1a1-4b08-a4c4-96ccb5679207.png)

**Comment by xheon** [comment]
The sample has ID 596b8941-3eb6-4f49-a7b1-8881118c07f2/0014, i.e refers to scene 596b8941-3eb6-4f49-a7b1-8881118c07f2
You can find all the camera poses in the provided "front3d-camposes.zip".

Since the reconstruction happens in camera-space the view point does not change. In order to move the reconstruction from grid space to camera space you can use:     
```
# define camera2frustum
camera2grid = torch.tensor([[33.3333, 0.0000, 0.0000, 114.7484],
                                [0.0000, 33.3333, 0.0000, 85.8808],
                                [0.0000, 0.0000, 33.3333, -13.3333],
                                [0.0000, 0.0000, 0.0000, 1.0000]])
 # get inverse of camera2frustum
 grid2camera = torch.inverse(camera2grid)
``` 
(obtained from lib/structures/frustum.py - compute_camera2frustum_transform() )

Hope that helps.

**Comment by ghost** [comment]
Thank you for your great project and reply!
